#release configuration
#Sat May 30 13:16:01 CDT 2026
scm.commentPrefix=[maven-release-plugin] 
exec.pomFileName=pom.xml
pushChanges=false
releaseStrategyId=default
project.scm.sc.fiji\:MaMuT.connection=scm\:git\:https\://github.com/trackmate-sc/MaMuT
project.scm.sc.fiji\:MaMuT.developerConnection=scm\:git\:git@github.com\:trackmate-sc/MaMuT
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
scm.tag=MaMuT-8.0.1
remoteTagging=true
project.dev.sc.fiji\:MaMuT=8.0.2-SNAPSHOT
exec.additionalArguments=-Dgpg.skip\=true 
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
projectVersionPolicyId=default
project.scm.sc.fiji\:MaMuT.tag=HEAD
project.rel.sc.fiji\:MaMuT=8.0.1
scm.url=scm\:git\:https\://github.com/trackmate-sc/MaMuT
scm.tagNameFormat=@{project.artifactId}-@{project.version}
pinExternals=false
preparationGoals=clean verify
project.scm.sc.fiji\:MaMuT.url=https\://github.com/trackmate-sc/MaMuT
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.snapshotReleasePluginAllowed=false
exec.activateProfiles=deploy-to-scijava
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
completedPhase=end-release
